// app/app/six-sigma/studies/capability/iddist/Theory.tsx
"use client";
import React, { useState } from "react";

type Lang = "es" | "en";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="space-y-2">
    <h3 className="font-bold text-base text-[#00674d] border-b border-gray-200 pb-1">
      {title}
    </h3>
    <div className="space-y-2 text-sm leading-relaxed">{children}</div>
  </section>
);

const Formula = ({ children }: { children: React.ReactNode }) => (
  <div className="my-2 px-4 py-3 bg-gray-50 border-l-4 border-[#00674d] font-serif text-base overflow-x-auto">
    {children}
  </div>
);

const V = ({ children }: { children: React.ReactNode }) => (
  <span className="italic">{children}</span>
);
const Sub = ({ children }: { children: React.ReactNode }) => (
  <sub className="text-[0.7em]">{children}</sub>
);
const Note = ({ children }: { children: React.ReactNode }) => (
  <div className="my-2 px-3 py-2 bg-amber-50 border-l-4 border-amber-400 text-sm">
    {children}
  </div>
);
const Warn = ({ children }: { children: React.ReactNode }) => (
  <div className="my-2 px-3 py-2 bg-red-50 border-l-4 border-red-500 text-sm">
    {children}
  </div>
);
const Cite = ({ children }: { children: React.ReactNode }) => (
  <sup className="text-[0.7em] text-[#00674d] font-semibold">[{children}]</sup>
);

const REFS = [
  "Anderson, T. W., & Darling, D. A. (1954). A test of goodness of fit. JASA, 49(268), 765\u2013769.",
  "Stephens, M. A. (1974). EDF statistics for goodness of fit and some comparisons. JASA, 69(347), 730\u2013737.",
  "D'Agostino, R. B., & Stephens, M. A. (1986). Goodness-of-Fit Techniques. Marcel Dekker.",
  "Box, G. E. P., & Cox, D. R. (1964). An analysis of transformations. JRSS-B, 26(2), 211\u2013252.",
  "Chou, Y., Polansky, A. M., & Mason, R. L. (1998). Transforming nonnormal data to normality in statistical process control. Journal of Quality Technology, 30(2), 133\u2013141.",
  "Johnson, N. L. (1949). Systems of frequency curves generated by methods of translation. Biometrika, 36(1/2), 149\u2013176.",
  "Benard, A., & Bos-Levenbach, E. C. (1953). Het uitzetten van waarnemingen op waarschijnlijkheidspapier. Statistica Neerlandica, 7, 163\u2013173.",
  "Cohen, A. C., & Whitten, B. J. (1988). Parameter Estimation in Reliability and Life Span Models. Marcel Dekker.",
];

const Refs = ({ title }: { title: string }) => (
  <section className="space-y-2">
    <h3 className="font-bold text-base text-[#00674d] border-b border-gray-200 pb-1">
      {title}
    </h3>
    <ol className="list-decimal pl-5 space-y-1 text-xs text-gray-600">
      {REFS.map((s, i) => (
        <li key={i}>{s}</li>
      ))}
    </ol>
  </section>
);

const ES = () => (
  <div className="space-y-5">
    <Section title="Para qué sirve">
      <p>
        El estudio de capacidad no normal exige elegir una distribuci&oacute;n, y
        esa elecci&oacute;n determina los PPM. Este m&oacute;dulo ajusta{" "}
        <strong>dieciseis candidatas</strong> a la vez y las pone una al lado de
        otra, para que la elecci&oacute;n sea una decisi&oacute;n y no una
        casualidad del desplegable.
      </p>
      <p>
        Cuatro son transformaciones y doce son distribuciones, cinco de ellas con
        par&aacute;metro de umbral.
      </p>
    </Section>

    <Section title="El gráfico de probabilidad, y por qué la recta es recta">
      <p>
        Casi todas las familias pueden escribirse como{" "}
        <strong>localizaci&oacute;n-escala</strong> en un espacio transformado:
      </p>
      <Formula>
        <V>u</V> = {"\u03BC"} + {"\u03C3"} {"\u00B7"} <V>g</V>(<V>p</V>)
      </Formula>
      <p>
        Para la Weibull, <V>u</V> = ln <V>x</V> y <V>g</V> es el cuantil del valor
        extremo menor; para la log-log&iacute;stica, <V>u</V> = ln <V>x</V> y{" "}
        <V>g</V> es el cuantil log&iacute;stico. Al dibujar <V>u</V> contra{" "}
        <V>g</V>(<V>p</V>), el ajuste sale como una <strong>recta</strong>, y el
        ojo juzga rectitud much&iacute;simo mejor que curvatura.
      </p>
      <p>
        Las posiciones de trazado son rangos medianos de Benard:{" "}
        <V>p</V><Sub>i</Sub> = (<V>i</V> {"\u2212"} 0,3) / (<V>n</V> + 0,4).
        <Cite>7</Cite>
      </p>
      <Note>
        La <strong>gamma es la excepci&oacute;n</strong>: no es
        localizaci&oacute;n-escala en ning&uacute;n espacio, as&iacute; que su
        ajuste aparece curvado y sin banda de confianza. Dibujar una banda ahi
        seria dibujar algo que no significa nada.
      </Note>
    </Section>

    <Section title="Anderson-Darling, y sus tablas">
      <Formula>
        <V>A</V><sup>2</sup> = {"\u2212"}<V>n</V> {"\u2212"} (1/<V>n</V>){" "}
        {"\u03A3"} (2<V>i</V> {"\u2212"} 1) [ ln <V>F</V>(<V>x</V><Sub>i</Sub>) +
        ln (1 {"\u2212"} <V>F</V>(<V>x</V><Sub>n+1{"\u2212"}i</Sub>)) ]
      </Formula>
      <p>
        La f&oacute;rmula es la misma para toda familia. Lo que cambia es el{" "}
        <strong>p-valor</strong>, porque la distribuci&oacute;n del
        estad&iacute;stico depende de qu&eacute; par&aacute;metros se hayan
        estimado.<Cite>2</Cite> Hay cuatro grupos de tablas: normales, valor
        extremo y Weibull, exponencial, y log&iacute;stica. La de la gamma
        adem&aacute;s <strong>depende del shape</strong>, con
        interpolaci&oacute;n en dos dimensiones.<Cite>3</Cite>
      </p>
      <Warn>
        <strong>Dieciseis contrastes sobre la misma muestra.</strong> El mayor de
        dieciseis p-valores est&aacute; sesgado al alza: el ganador siempre parece
        mejor de lo que es. Este panel sirve para <em>descartar</em> familias que
        fallan con claridad, no para coronar una por una diferencia de pelo.
      </Warn>
    </Section>

    <Section title="Los umbrales, y la razón de verosimilitudes">
      <p>
        Cinco candidatas a&ntilde;aden un par&aacute;metro de umbral. Un modelo
        con un par&aacute;metro m&aacute;s <strong>casi siempre ajusta mejor</strong>,
        as&iacute; que un AD menor no prueba nada por si solo. La columna{" "}
        <strong>LRT P</strong> es la que decide:
      </p>
      <Formula>
        {"\u039B"} = 2 [ ln <V>L</V><Sub>3</Sub> {"\u2212"} ln <V>L</V><Sub>2</Sub>{" "}
        ] {"\u007E"} {"\u03C7"}<sup>2</sup><Sub>1</Sub>
      </Formula>
      <p>
        Un LRT P grande dice que la mejora <strong>no</strong> justifica el
        par&aacute;metro extra. Con estos datos, el 3P Weibull da 0,778: el umbral
        es prescindible. El 3P lognormal da 0,000: ahi si aporta.
      </p>
      <Warn>
        La verosimilitud del umbral <strong>diverge</strong> cuando este se acerca
        al m&iacute;nimo muestral. El optimizador va acotado por debajo del
        m&iacute;nimo, y aun asi hay casos {"\u2014"} la gamma de tres
        par&aacute;metros con estos datos {"\u2014"} en que el perfil es plano y el
        resultado depende del punto de arranque. Es la misma
        condici&oacute;n que Minitab se&ntilde;ala diciendo que no existe la matriz
        de varianzas-covarianzas.
      </Warn>
      <Note>
        En el exponencial de dos par&aacute;metros el umbral <em>no</em> es el
        m&aacute;ximo de verosimilitud, que ser&iacute;a el m&iacute;nimo muestral,
        sino el estimador corregido de sesgo{" "}
        <V>x</V><Sub>min</Sub> {"\u2212"} <V>s</V>/<V>n</V>.<Cite>8</Cite> Por eso
        su LRT P sale 1,000: el modelo de tres par&aacute;metros ajusta algo{" "}
        <em>peor</em> que el de dos, y el estad&iacute;stico es negativo.
      </Note>
    </Section>

    <Section title="Transformar o cambiar de distribución">
      <p>
        Box-Cox busca la potencia que m&aacute;s normaliza:<Cite>4</Cite>
      </p>
      <Formula>
        <V>y</V> = (<V>x</V><sup>{"\u03BB"}</sup> {"\u2212"} 1) / {"\u03BB"}
        {"\u00A0\u00A0"}({"\u03BB"} {"\u2260"} 0),{"\u00A0\u00A0"}
        <V>y</V> = ln <V>x</V> {"\u00A0"}({"\u03BB"} = 0)
      </Formula>
      <p>
        Johnson es m&aacute;s flexible: tres familias {"\u2014"} S<Sub>B</Sub>{" "}
        acotada, S<Sub>L</Sub> lognormal, S<Sub>U</Sub> no acotada {"\u2014"} y se
        elige por el procedimiento de Chou, recorriendo una rejilla de valores{" "}
        <V>z</V> y quedandose con la de mejor AD.<Cite>5</Cite>
      </p>
      <Warn>
        Una transformaci&oacute;n cambia la escala. Los l&iacute;mites de
        especificaci&oacute;n hay que transformarlos igual, y{" "}
        <strong>los indices resultantes no son comparables</strong> con los de un
        estudio en unidades originales. Si el proceso tiene una
        distribuci&oacute;n con sentido fisico, ajustarla es preferible a
        transformar.
      </Warn>
    </Section>

    <Section title="Ejemplo resuelto">
      <p>
        <em>Cycletime</em>, 200 observaciones. Media 98,2418 y mediana 67,7606:
        la asimetria de 2,05 ya anticipa que la normal no va a servir, y su AD de
        8,77 lo confirma.
      </p>
      <p>
        Ganan tres candidatas con p por encima de 0,25: la <strong>gamma</strong>{" "}
        (AD 0,434), la <strong>Johnson</strong> (0,384) y la{" "}
        <strong>Box-Cox</strong> (0,419). La Weibull queda en 0,477 con p = 0,241.
      </p>
      <Note>
        Y aqui esta la leccion. Si el estudio de capacidad se hizo con Weibull
        porque era la opcion por defecto, <strong>la gamma ajustaba mejor</strong>{" "}
        y los PPM habrian salido distintos. Entre transformar y ajustar una gamma,
        la gamma gana: mismo nivel de ajuste, sin cambiar de escala y sin tener
        que transformar tambien las especificaciones.
      </Note>
    </Section>

    <Refs title="Bibliografía" />
  </div>
);

const EN = () => (
  <div className="space-y-5">
    <Section title="What it is for">
      <p>
        A nonnormal capability study requires choosing a distribution, and that
        choice determines the PPM. This module fits{" "}
        <strong>sixteen candidates</strong> at once and puts them side by side, so
        that the choice is a decision rather than an accident of which entry the
        dropdown offered first.
      </p>
      <p>
        Four are transformations and twelve are distributions, five of them with a
        threshold parameter.
      </p>
    </Section>

    <Section title="The probability plot, and why the line is straight">
      <p>
        Nearly every family can be written as{" "}
        <strong>location-scale</strong> in some transformed space:
      </p>
      <Formula>
        <V>u</V> = {"\u03BC"} + {"\u03C3"} {"\u00B7"} <V>g</V>(<V>p</V>)
      </Formula>
      <p>
        For the Weibull, <V>u</V> = ln <V>x</V> and <V>g</V> is the smallest
        extreme value quantile; for the loglogistic, <V>u</V> = ln <V>x</V> and{" "}
        <V>g</V> is the logistic quantile. Plotting <V>u</V> against <V>g</V>(
        <V>p</V>) makes the fit a <strong>straight line</strong>, and the eye
        judges straightness far better than curvature.
      </p>
      <p>
        Plotting positions are Benard median ranks, (<V>i</V> {"\u2212"} 0.3) / (
        <V>n</V> + 0.4).<Cite>7</Cite>
      </p>
      <Note>
        The <strong>gamma is the exception</strong>: it is not location-scale in
        any space, so its fit appears curved and carries no confidence band.
        Drawing a band there would be drawing something that means nothing.
      </Note>
    </Section>

    <Section title="Anderson-Darling, and its tables">
      <Formula>
        <V>A</V><sup>2</sup> = {"\u2212"}<V>n</V> {"\u2212"} (1/<V>n</V>){" "}
        {"\u03A3"} (2<V>i</V> {"\u2212"} 1) [ ln <V>F</V>(<V>x</V><Sub>i</Sub>) +
        ln (1 {"\u2212"} <V>F</V>(<V>x</V><Sub>n+1{"\u2212"}i</Sub>)) ]
      </Formula>
      <p>
        The formula is the same for every family. What changes is the{" "}
        <strong>p-value</strong>, because the distribution of the statistic
        depends on which parameters were estimated.<Cite>2</Cite> There are four
        groups of tables: normal, extreme value and Weibull, exponential, and
        logistic. The gamma table additionally{" "}
        <strong>depends on the shape</strong>, with two-dimensional
        interpolation.<Cite>3</Cite>
      </p>
      <Warn>
        <strong>Sixteen tests on one sample.</strong> The largest of sixteen
        p-values is biased upward: the winner always looks better than it is. Use
        this panel to <em>rule out</em> families that clearly fail, not to crown
        one on a hairline difference.
      </Warn>
    </Section>

    <Section title="Thresholds, and the likelihood ratio">
      <p>
        Five candidates add a threshold parameter. A model with one more
        parameter <strong>almost always fits better</strong>, so a lower AD proves
        nothing on its own. The <strong>LRT P</strong> column is what decides:
      </p>
      <Formula>
        {"\u039B"} = 2 [ ln <V>L</V><Sub>3</Sub> {"\u2212"} ln <V>L</V><Sub>2</Sub>{" "}
        ] {"\u007E"} {"\u03C7"}<sup>2</sup><Sub>1</Sub>
      </Formula>
      <p>
        A large LRT P says the improvement does <strong>not</strong> justify the
        extra parameter. On these data the 3P Weibull gives 0.778: the threshold
        is dispensable. The 3P lognormal gives 0.000: there it earns its place.
      </p>
      <Warn>
        The likelihood of the threshold <strong>diverges</strong> as it approaches
        the sample minimum. The search is bounded below the minimum, and even so
        there are cases {"\u2014"} the three-parameter gamma on these data{" "}
        {"\u2014"} where the profile is flat and the answer depends on the
        starting point. This is the same condition Minitab reports as a missing
        variance/covariance matrix.
      </Warn>
      <Note>
        For the two-parameter exponential the threshold is <em>not</em> the
        maximum-likelihood estimate, which would be the sample minimum, but the
        bias-corrected estimate <V>x</V><Sub>min</Sub> {"\u2212"} <V>s</V>/
        <V>n</V>.<Cite>8</Cite> That is why its LRT P comes out at 1.000: the
        three-parameter model fits slightly <em>worse</em> than the
        two-parameter one, and the statistic is negative.
      </Note>
    </Section>

    <Section title="Transform or change distribution">
      <p>
        Box-Cox searches for the power that best normalises:<Cite>4</Cite>
      </p>
      <Formula>
        <V>y</V> = (<V>x</V><sup>{"\u03BB"}</sup> {"\u2212"} 1) / {"\u03BB"}
        {"\u00A0\u00A0"}({"\u03BB"} {"\u2260"} 0),{"\u00A0\u00A0"}
        <V>y</V> = ln <V>x</V> {"\u00A0"}({"\u03BB"} = 0)
      </Formula>
      <p>
        Johnson is more flexible: three families {"\u2014"} S<Sub>B</Sub> bounded,
        S<Sub>L</Sub> lognormal, S<Sub>U</Sub> unbounded {"\u2014"} selected by
        Chou's procedure, sweeping a grid of <V>z</V> values and keeping the best
        AD.<Cite>5</Cite>
      </p>
      <Warn>
        A transformation changes the scale. Specification limits must be
        transformed the same way, and{" "}
        <strong>the resulting indices are not comparable</strong> with those from
        a study in original units. If the process has a distribution with a
        physical meaning, fitting it is preferable to transforming.
      </Warn>
    </Section>

    <Section title="Worked example">
      <p>
        <em>Cycletime</em>, 200 observations. Mean 98.2418 and median 67.7606: a
        skewness of 2.05 already says the normal will not do, and its AD of 8.77
        confirms it.
      </p>
      <p>
        Three candidates come out above p = 0.25: the <strong>gamma</strong> (AD
        0.434), the <strong>Johnson</strong> (0.384) and{" "}
        <strong>Box-Cox</strong> (0.419). The Weibull sits at 0.477 with p =
        0.241.
      </p>
      <Note>
        And there is the lesson. If the capability study was run with a Weibull
        because that was the default, <strong>the gamma fitted better</strong> and
        the PPM would have come out differently. Between transforming and fitting
        a gamma, the gamma wins: the same quality of fit, without changing scale
        and without having to transform the specifications too.
      </Note>
    </Section>

    <Refs title="References" />
  </div>
);

export default function IdDistTheory() {
  const [lang, setLang] = useState<Lang>("es");
  return (
    <div className="space-y-4">
      <div className="flex justify-end gap-1">
        {(["es", "en"] as Lang[]).map((l) => (
          <button
            key={l}
            onClick={() => setLang(l)}
            className={`px-3 py-1 text-xs rounded border ${
              lang === l
                ? "bg-[#00674d] text-white border-[#00674d]"
                : "bg-white text-gray-600 border-gray-300"
            }`}
          >
            {l.toUpperCase()}
          </button>
        ))}
      </div>
      {lang === "es" ? <ES /> : <EN />}
    </div>
  );
}
